apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
    - image: dritaaa/carp-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
